CREATE DATABASE MySQL;
use MySQL;
SELECT DATABASE();
CREATE TABLE GUVI
(
ID     INT       AUTO_INCREMENT PRIMARY KEY NOT NULL,
NAME   CHAR(30)                             NOT NULL,
AGE    INT(3)                               NOT NULL,
COURSE CHAR(25)                             NOT NULL
);
INSERT INTO GUVI (NAME,AGE,COURSE) VALUES('HARIPRASATH',21,'MySQL');
INSERT INTO GUVI (NAME,AGE,COURSE) VALUES('MUGUNTHAN',21,'PYTHON');
INSERT INTO GUVI (NAME,AGE,COURSE) VALUES('RATHNAKUMAR',21,'JAVA');
INSERT INTO GUVI (NAME,AGE,COURSE) VALUES('NITHYANANDHAN',21,'MySQL');
INSERT INTO GUVI (NAME,AGE,COURSE) VALUES('GNANASEKAR',21,'MySQL');
CREATE INDEX idx_name ON GUVI (NAME);
DESC GUVI;
CREATE VIEW LTD AS
SELECT * FROM GUVI WHERE COURSE = 'MySQL';
DROP VIEW LTD;
